### ISSUE TITLE
KeyError: 'g_a.0.weight'  in Model update

### ISSUE THREAD

**Issue by jsw-zorro** [InterDigitalInc/CompressAI#57]
Hi all,

I am trying to finetune a pre-trained model on my dataset. The packages version I used are listed as follows:
```
PyTorch: Version: 1.8.1+cu111   
CompressAI: Version: 1.1.4
```

I mainly modified one line in `examples/train.py` and changed it to `finetune.py`. The line I modified changed to the following:
```python
net = models[args.model](quality=args.quality, metric="mse", pretrained=True)
``` 
And I used the following script to finetune the pretrained model and save it to a checkpoint.
```bash
python finetune.py -m cheng2020-anchor -q 1 -d ../../test-pictures-finetuned --save --cuda
```

And it successfully generates the checkpoints I need. Then, I follow the steps provided in the tutorial. To update the CDF, and export the checkpoint.
I did it with the following command.
```
python -m compressai.utils.update_model --architecture mean-scale-hyperprior -n cheng2020-anchor-finetuned -d ../updated-checkpoints checkpoint_best_loss.pth.tar
```
And the error occurred: 
```bash
Traceback (most recent call last):                                                                                                                                                       
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                                                                   
    return _run_code(code, main_globals, None,                                                                                                                                           
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code                                                                                                                              
    exec(code, run_globals)                                                                                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/compressai/utils/update_model/__main__.py", line 139, in <module>                                                                         
    main(sys.argv[1:])                                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/compressai/utils/update_model/__main__.py", line 110, in main                                                                             
    net = model_cls.from_state_dict(state_dict)                                                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/compressai/models/priors.py", line 274, in from_state_dict                                                                                
    N = state_dict["g_a.0.weight"].size(0)                                                                                                                                               
KeyError: 'g_a.0.weight' 
```
I changed the `--architecture` to all other architectures, `{factorized-prior,jarhp,mean-scale-hyperprior,scale-hyperprior} `. None of these works. Could you help me with this?
Thanks a lot!

**Comment by jbegaint** [comment]
You need to use the `cheng2020-anchor` for the `--architecture` option in the command line.

**Comment by jsw-zorro** [comment]
Hi @jbegaint, thanks a lot for your response.
I tried to use the `cheng2020-anchor` for the `--architecture` option. And receives the errors:
```bash
usage: __main__.py [-h] [-n NAME] [-d DIR] [--no-update]                                                                                                                                 
                   [--architecture {factorized-prior,jarhp,mean-scale-hyperprior,scale-hyperprior}]                                                                                      
                   filepath                                                                                                                                                              
__main__.py: error: argument --architecture: invalid choice: 'cheng2020-anchor' (choose from 'factorized-prior', 'jarhp', 'mean-scale-hyperprior', 'scale-hyperprior')  
```
I also check with the code, there's no option for the `cheng2020-anchor` indeed?
The command I used is as the following:
```bash
python -m compressai.utils.update_model --architecture cheng2020-anchor -n cheng2020-anchor-finetuned -d ../updated-checkpoints checkpoint_best_loss.pth.tar    
```
Thanks a lot for your feedback.

**Comment by jbegaint** [comment]
yes my bad, this is fixed in the development version but not the stable one. I'll update the pypi package right away.

**Comment by jsw-zorro** [comment]
Hi Jean @jbegaint ,
Thanks a lot for your help. However, I just updated my compressai package to `V1.1.5`. And run the command above. However, the error still occurs.
```bash
Traceback (most recent call last):                                                                                                                                                       
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                                                                   
    return _run_code(code, main_globals, None,                                                                                                                                           
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code                                                                                                                              
    exec(code, run_globals)                                                                                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/compressai/utils/update_model/__main__.py", line 146, in <module>                                                                         
    main(sys.argv[1:])                                                                                                                                                                   
  File "/usr/local/lib/python3.8/dist-packages/compressai/utils/update_model/__main__.py", line 117, in main                                                                             
    net = model_cls.from_state_dict(state_dict)                                                                                                                                          
  File "/usr/local/lib/python3.8/dist-packages/compressai/models/waseda.py", line 93, in from_state_dict                                                                                 
    N = state_dict["g_a.0.conv1.weight"].size(0)                                                                                                                                         
KeyError: 'g_a.0.conv1.weight' 
```
Could you check with this?

**Comment by jsw-zorro** [comment]
Hi Jean @jbegaint , Never mind. I found I just need to regenerate the checkpoint and then it can be updated using the updated pip package. Thanks for the help.

**Comment by jbegaint** [comment]
Great :-).
